apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymb
  labels:
    app: deploymb
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
     matchLabels:
       app: deploymb
  template:
    metadata:
      labels:
        app: deploymb
    spec:
      containers:
        - name: http
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
               memory: 100Mi
               cpu: 25m
            limits:
               memory: 150Mi
               cpu: 50m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoScaler
metadata:
  name: hpa
spec:
   scalerTargetRef:
     apiVersion: apps/v1
     kind: Deployment
     name: deploymb
   minReplicas: 1
   maxReplicas: 4
   metrics:
     - type: Resources
       resource: 
          name: cpu
          target: 
            type: Utilization
            averageUtilization: 50