apiVersion: v1
kind: Pod
metadata:
   name: travis
   labels:
      app: new-app
spec: 
   containers:
     - name: nginx
       image: nginx:latest
       ports:
        - containerPort: 80
          protocol: TCP
     - name: tomcat
       image: tomcat:latest
       ports:
       - containerPort: 80
         protocol: TCP